version: 2.1
workflows:
  build-test-deploy:
    jobs:
      build:
        docker:
          - image: circleci/openjdk:8-jdk-stretch
        steps:
          - checkout
          - run:
              name: The First Step
              command: |
                echo 'Hello World!'
                echo 'This is the delivery pipeline'
