version: 2.1
jobs:
  checkout_test_and_build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      APP_NAME: "accounting-api-service"
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Setting_Version
          command: |
            echo 'mvn versions:set -DnewVersion=${CIRCLE_TAG}'
            echo ${APP_NAME}
      - run:
          name: Maven_Enforcer
          command: |
            echo 'mvn enforcer:enforce'
      - run:
          name: Maven_Sonar
          command: |
            echo 'mvn install sonar:sonar'
            echo 'mvn clean deploy -Dmaven.test.skip=true'
      - run:
          name: Integration Tests Backend
          command: |
            echo 'git clone https://github.boozallencsn.com/AI/integration-test-backend.git'
            echo 'cd integration-test-backend && mvn test -Dtest=QualityGateTest -Dsonar.project.key=com.bah.ai.api:accounting-api-service'

## This is the 2nd job definition
  promote_to_environments:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Calling Spinnaker
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  version: 2
  build_release:
    jobs:
      - checkout_test_and_build
  promote_to_master:
    jobs:
      - checkout_test_and_build
      - promote_to_environments:
          requires:
          - checkout_test_and_build
