version: 2.1
jobs:
  checkout_and_build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step
          command: |
            echo 'Hello World 2!'
            echo 'This is the delivery pipeline'
# Second Job definition
  second_job:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  version: 2
  accounting-api-service:
    jobs:
      - checkout_and_build
      -
